---
title: Simple Traefik Identity

showcase: True
  
images:
  - https://github.com/ms-jpq/simple-traefik-identity/raw/xp/preview/login.png
  - https://github.com/ms-jpq/simple-traefik-identity/raw/xp/preview/logoff.png
