version: "3.7"

services:
  #
  # This file is used for development
  #
  sti:
    build: .
    container_name: sti
    labels:
      - traefik.http.routers.sti.entrypoints=traefik
      - traefik.http.services.sti.loadbalancer.server.port=5050
      - traefik.http.middlewares.auth.forwardauth.address=http://sti
    environment:
      - TZ=${TZ}
    ports:
      - 5050:5050
    volumes:
      - ./config/conf.yml:/sti/config/conf.yml

  traefik:
    image: traefik
    container_name: traefik
    labels:
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.http.routers.traefik.middlewares=auth
      - traefik.http.routers.traefik.rule=HostRegexp("{any:.*}") && PathPrefix("/dashboard", "/api")
    environment:
      - TZ=${TZ}
    ports:
      - 8080:80
      - 8888:8080
    command: >
      - --providers.docker.watch=true
      - --api.insecure=true
      - --api.dashboard=true
      - --log.level=DEBUG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  whoami:
    image: containous/whoami
    container_name: whoami
    labels:
      - traefik.http.services.whoami.loadbalancer.server.port=80
      - traefik.http.routers.whoami.middlewares=auth
      - traefik.http.routers.whoami.rule=HostRegexp("{any:.*}")
    environment:
      - TZ=${TZ}
