version: "3.7"

services:
  #
  # This file is used for development
  #
  sti:
    build: .
    container_name: sti
    ports:
      - 5050:5050
    environment:
      - TZ=${TZ}
    volumes:
      - ./config/conf.yml:/sti/config/conf.yml
